# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Base Camp
tagline:          'First attempt at the web'
description:      'Markdown-based approach for projects.'
url:              http://asshah4.github.io
baseurl:          /

author:
  name:           'Anish Shah'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/asshah4/asshah4.github.io

# Includes icon in footer for footer links based on username
  github: asshah4
  twitter:

# Gems
plugins: [jekyll-paginate, jekyll-gist, redcarpet]
