# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            base camp
tagline:          'First attempt at the web'
description:      'Markdown-based approach for all the things.'
url:              http://asshah4.github.io
baseurl:          

author:
  name:           'Anish Shah'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          0.2.0

github:
  repo:           https://github.com/asshah4/asshah4.github.io

# Includes icon in footer for footer links based on username
  github: asshah4
  twitter:

# Gems
plugins: [jekyll-paginate, jekyll-gist]
