# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            base camp
tagline:          'First attempt at the web'
description:      'Markdown-based approach for all the things'
url:              http://asshah4.github.io
baseurl:          

author:
  name: 'Anish Shah'
  email: 'asshah4[at]email[dot]emory[dot]edu'
  github: asshah4
  facebook: asshah4

paginate:         5

# Custom vars
version:          0.3.0

github:
  repo:           https://github.com/asshah4/asshah4.github.io

# Social media links and icons

# Gems
plugins: [jekyll-paginate, jekyll-gist]
