project:
  type: website
  output-dir: docs

website:
  title: "Anish S. Shah, MD|MS"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Me
      - text: Curriculum Vitae
        href: https://shah-in-boots.github.io/cv
      - text: Research
        href: https://shah-in-boots.github.io/research
      - text: Clinical
        href: https://shah-in-boots.github.io/clinical
      - text: Talks
        href: talks.html
      - text: Software
        menu:
          - text: "R/card"
            href: https://shah-in-boots.github.io/card
          - text: "R/hrd"
            href: https://shah-in-boots.github.io/hrd
          - text: "R/EGM"
            href: https://shah-in-boots.github.io/EGM
          - text: "R/orbs"
            href: https://shah-in-boots.github.io/orbs
          - text: "R/rmdl"
            href: https://shah-in-boots.github.io/rmdl
          - text: "R/rcr"
            href: https://shah-in-boots.github.io/rcr
      - text: Notes
        href: https://shah-in-boots.github.io/notes
    right:
      - icon: github
        href: http://github.com/shah-in-boots/shah-in-boots.github.io
  page-navigation: true
  page-footer: "Copyright (c) 2024, Anish. S. Shah, MD, MS"

bibliography:
  - ../bibliography/publications.bib
  - ../bibliography/cardiology.bib
  - ../bibliography/arrhythmia.bib
  - ../bibliography/computational.bib
  - ../bibliography/epidemiology.bib

csl: ../bibliography/jacc.csl

format:
  html:
    theme:
      light:
        - flatly
        - colors.scss
      dark:
        - darkly
        - colors.scss
    highlight: solarized-light
    toc: true
    toc_float: true
