project:
  type: website
  output-dir: docs

website:
  title: "Anish S. Shah, MD|MS"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Me
      - text: Curriculum Vitae
        href: https://shah-in-boots.github.io/cv/vitae.pdf
      - text: Research
        href: https://shah-in-boots.github.io/research
      - text: Clinical
        href: https://shah-in-boots.github.io/clinical
      - text: Talks
        href: talks.html
      - text: Software
        menu:
          - text: "R/orbs"
            href: https://shah-in-boots.github.io/orbs
          - text: "R/rmdl"
            href: https://shah-in-boots.github.io/rmdl
          - text: "R/EGM"
            href: https://shah-in-boots.github.io/EGM
          - text: "R/card"
            href: https://shah-in-boots.github.io/card
          - text: "R/rcr"
            href: https://shah-in-boots.github.io/rcr
          - text: "R/hrd"
            href: https://shah-in-boots.github.io/hrd
      - text: Notes
        href: https://shah-in-boots.github.io/notes
    right:
      - icon: envelope
        href: mailto:ashah282@uic.edu
      - icon: github
        href: http://github.com/shah-in-boots
      - icon: twitter
        href: https://twitter.com/shah_in_boots
      - icon: linkedin
        href: https://www.linkedin.com/in/anish-shah-326991177/
  page-navigation: true
  page-footer: "Copyright (c) 2024, Anish. S. Shah, MD, MS"

bibliography:
  - ../bibliography/publications.bib
  - ../bibliography/cardiology.bib
  - ../bibliography/arrhythmia.bib
  - ../bibliography/computational.bib
  - ../bibliography/epidemiology.bib

csl: ../bibliography/jacc.csl

format:
  html:
    theme:
      - flatly
      - colors.scss
    highlight: solarized-light
    toc: true
    toc_float: true
  revealjs:
    theme:
      - simple
      - colors.scss
    slide-tone: true
    fig-cap-location: bottom
    fig-align: center
    fig-responsive: true
