project:
  type: website
  output-dir: docs

website:
  title: "Anish S. Shah, MD|MS"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Me
      - text: Curriculum Vitae
        href: https://asshah4.github.io/cv/vitae.pdf
      - text: Research
        href: https://asshah4.github.io/research
      - text: Clinical
        href: https://asshah4.github.io/clinical
      - text: Talks
        href: talks.html
      - text: Projects
        menu:
          - text: "{ouroborus}"
            href: https://asshah4.github.io/ouroborus
          - text: "{volundr}"
            href: https://asshah4.github.io/volundr
          - text: "{durandal}"
            href: https://asshah4.github.io/durandal
      - text: Notes
        href: https://asshah4.github.io/notes
    right:
      - icon: envelope
        href: mailto:ashah282@uic.edu
      - icon: github
        href: http://github.com/asshah4
      - icon: twitter
        href: https://twitter.com/shah_in_boots
      - icon: linkedin
        href: https://www.linkedin.com/in/anish-shah-326991177/
  page-navigation: true
  page-footer: "Copyright (c) 2023, Anish. S. Shah, MD, MS"

format:
  html:
    theme: [flatly, styles.scss]
    highlight: solarized-light
    css: styles.scss
    toc: true
    toc_float: true
  revealjs:
    theme: [simple, styles.scss]
    slide-tone: true
    fig-cap-location: bottom
    fig-align: center
    fig-responsive: true

bibliography: ../bibliography/Research.bib
csl: ../bibliography/jacc.csl
