---
title: Talks
---

Here is a collection of select formal presentations that I've given. Feel free to reference as needed. [\#FOAMed](https://twitter.com/hashtag/foamed) They range in variety of topics.

__February 01, 2021__ A journal club on [GALACTIC-HF](https://asshah4.github.io/clinical/journal_club/02-01-21_galactic-hf/galactic-hf.html), which was the one of the first looks at an oral inotropic agent that did not increase cardiovascular mortality (as compared with milrinone and dobutamine infusions).

__December 20, 2020__ As a cardiology fellow, we have clinical case conferences to review interesting or puzzling cases with evidence-based analysis. Here is an interesting case of [restrictive cardiomyopathy](http:://asshah4-github.io/clinical/cases/12-14-20_biatrial-enlargement/biatrial-enlargement.html), including the work-up and a brief differential on etiologies.

__February 18, 2019__ As a medical resident, we complete a _senior grand rounds_, a summative talk of an area of our choosing. I researched psychological triggers for sudden cardiac death, and gave a "chalk talk" style [presentation](https://docs.google.com/presentation/d/e/2PACX-1vSc3jQ0INW8dfKsb2zgs9LrizLf0MRCf4s9W2n9AomYL8B3YtAoYxoo-inxdrMaAV4xAE6Q_dtvFRP9/pub?start=false&loop=false&delayms=3000). There was an associated [handout](https://docs.google.com/document/d/e/2PACX-1vQsGMyGGko6u8kAF8u6C1lmFUjJE7DW_uhN0tqfCNkvOFMv2Pgpwqx3d2kpAKroxW7jDS5LsqKXhaYm/pub) and [notes with references](https://docs.google.com/document/d/e/2PACX-1vRPOH1kDLA1RfL7xJYRLJ5oqbpriSM_gkW04Z76_4hOboBKY7twWt4rUsiqjz6dKzePgkQ9w1iTDEg1/pub). The concept of psychological triggers as affecting the ventricular substrate is fascinating, particularly as we learn more of the role of the autonomic nervous system in cardiovascular disease.

__March 21, 2018__ With literature from early-terminated trials during 2018, I gave a [journal club lecture](https://docs.google.com/presentation/d/e/2PACX-1vRsD-2d4edr4G1Y5pEBvGMnDoG5PErGIJu8_F1jrJlso9DwvfCo5rwKINpn16_boiHfJa_wkRmgZGQH/pub?start=false&loop=false&delayms=3000) on the updated guidelines on thrombectomy for ischemic strokes. My [notes](https://docs.google.com/document/d/e/2PACX-1vRJx-3n9nAP1oSieonEs8mmPcsoHwyvUtJNcRJTTiARtNxQuGfIxJwMtK-FJFVrs2nOOMvcC_0243-O/pub) for it serve as a reference and series of citations, with a [handout](https://docs.google.com/document/d/e/2PACX-1vTUNgylVolLVZ9YkrqkADNB9s2XM6Ee9OFvUYprZ-T7FxPEKJTmI9M0YhTuKeO12xbwFswCmV-j_oP4/pub) to improve viewer interaction. The largest issue I find was in the interpretation of their __Table 1__ showing non-adjusted odds ratios for an ordinal scale, listed next to a P-value.

__March 15, 2018__ As a resident, there is a shift into becoming a teacher to both medical students and near-peers while being a learner as well. A significant amount of residents actually develop critical failures in the learning process. Here is an approach I [presented](https://docs.google.com/presentation/d/e/2PACX-1vSKWQvLnS7C12s44EHJAk4ewrdwYM7WvJrLigndn9uZCz8m16cqDPvPtYMkwosxTG-7Cw3QEWkR-fHT/pub?start=false&loop=false&delayms=3000), with supporting [literature](https://docs.google.com/document/d/e/2PACX-1vQoE0lM5dsy5r3Vtm9iwJtxXZccCqN7zW7yVkhLhWVlLgvjPfe30Ud-Z27E0ngE3GiyMP727JxF8IlB/pub) and an [outline](https://docs.google.com/document/d/e/2PACX-1vQd5LzOgEjZi2kNC5XwvUrxU1IzpFmt6fiP8MoppCfwYrpEASLHa4R-5J0CHpz7zvWVZIIXrryYSao_/pub) to be shared.
